### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rahulps1000** [salmanmemon7/Threads#2]
Hi,
I recently came to see your repo and I was amazed to find the devtools unlocked ig.
Can you guide me through the process of creating/reverse engineering the apps along with the tools you use. Also post in the Readme.md, and that will increase the authenticity of your repo.

**Comment by salmanmemon7** [comment]
> Hi,
> I recently came to see your repo and I was amazed to find the devtools unlocked ig.
> Can you guide me through the process of creating/reverse engineering the apps along with the tools you use. Also post in the Readme.md, and that will increase the authenticity of your repo.

Hello 🤗. Good to Know welcome to repo .
Opening Devloper settings is not easy work for very first time . I do manage all things alone . For Readme.md I am currently thinking what to put. I am looking for it .

Thanks. if you like repo i hope for a star

**Comment by rahulps1000** [comment]
Thanks for the response.

I am very much interested in this kind of stuffs but I am not sure how and where to start. If you can guide and help me on it, I am happy to contribute towards your repo.

Currently the repo is seems empty, once you update the readme and other details, surely you will receive stars.

**Comment by salmanmemon7** [comment]
> Thanks for the response.
> 
> I am very much interested in this kind of stuffs but I am not sure how and where to start. If you can guide and help me on it, I am happy to contribute towards your repo.
> 
> Currently the repo is seems empty, once you update the readme and other details, surely you will receive stars.

Can We Talk on Telegram
t.me/salman_memon

**Comment by salmanmemon7** [comment]
> > Thanks for the response.
> > I am very much interested in this kind of stuffs but I am not sure how and where to start. If you can guide and help me on it, I am happy to contribute towards your repo.
> > Currently the repo is seems empty, once you update the readme and other details, surely you will receive stars.
> 
> Can We Talk on Telegram t.me/salman_memon
I have updated many things see
And 
Add new update just now
